export const SAVE_PARTY = 'SAVE_PARTY';
export const FETCH_PARTIES = 'FETCH_PARTIES';
export const FILTER_PARTIES = 'FILTER_PARTIES';
export const FILTER_MERCHANTS = 'FILTER_MERCHANTS';
export const FETCH_PARTY = 'FETCH_PARTY';
export const EDIT_PARTY = 'EDIT_PARTY';
export const DELETE_PARTY = 'DELETE_PARTY';
export const FETCH_OPENING_BALANCE_OF_PARTY = 'FETCH_OPENING_BALANCE_OF_PARTY';
export const FETCH_STATUS_OF_SINGLE_PARTY = 'FETCH_STATUS_OF_SINGLE_PARTY';

export const SAVE_AVAK = 'SAVE_AVAK';
export const FETCH_AVAKS = 'FETCH_AVAKS';
export const FETCH_AVAKS_BY_PARTY_ID = 'FETCH_AVAKS_BY_PARTY_ID';
export const EDIT_AVAK = 'EDIT_AVAK';
export const DELETE_AVAK = 'DELETE_AVAK';
export const FETCH_LAST_AVAK = 'FETCH_LAST_AVAK';
export const FETCH_NEW_RECEIPT_NUMBER = 'FETCH_NEW_RECEIPT_NUMBER';
export const FETCH_TRANSACTIONS_OF_SINGLE_PARTY = 'FETCH_TRANSACTIONS_OF_SINGLE_PARTY';
export const SHOW_PARTY_SEARCH_POPUP = 'SHOW_PARTY_SEARCH_POPUP';

export const SAVE_JAVAK = 'SAVE_JAVAK';
export const FETCH_JAVAKS = 'FETCH_JAVAKS';
export const EDIT_JAVAK = 'EDIT_JAVAK';
export const DELETE_JAVAK = 'DELETE_JAVAK';
export const FETCH_AVAKS_OF_PARTY = 'FETCH_AVAKS_OF_PARTY';
export const FETCH_JAVAKS_BY_PARTY_ID = 'FETCH_JAVAK_LOTS_BY_AVAK_ID';
export const FETCH_LAST_JAVAK = 'FETCH_LAST_JAVAK';
export const FETCH_NEW_RECEIPT_NUMBER_FOR_JAVAK = 'FETCH_NEW_RECEIPT_NUMBER_FOR_JAVAK';
export const FETCH_JAVAKS_OF_SINGLE_MERCHANT = 'FETCH_JAVAKS_OF_SINGLE_MERCHANT';

export const SAVE_JAVAK_LOT = 'SAVE_JAVAK_LOT';
export const DELETE_JAVAK_LOT = 'DELETE_JAVAK_LOT';
export const FETCH_JAVAK_LOTS = 'FETCH_JAVAK_LOTS';
export const FETCH_JAVAK_LOTS_BY_JAVAK_ID = 'FETCH_JAVAK_LOTS_BY_JAVAK_ID';
export const FETCH_JAVAK_LOTS_BY_AVAK_ID = 'FETCH_JAVAK_LOTS_BY_AVAK_ID';
export const REMOVE_TEMP_JAVAK_LOTS = 'REMOVE_TEMP_JAVAK_LOTS';
export const MODIFY_AVAKS = 'MODIFY_AVAKS';

export const SAVE_TRANSACTION = 'SAVE_TRANSACTION';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_BY_PARTY_ID = 'FETCH_TRANSACTIONS_BY_PARTY_ID';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const FETCH_LAST_TRANSACTION = 'FETCH_LAST_TRANSACTION';
export const FETCH_NEW_RECEIPT_NUMBER_OF_TRANSACTION = 'FETCH_NEW_RECEIPT_NUMBER_OF_TRANSACTION';

export const SAVE_ITEM = 'SAVE_ITEM';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

export const SAVE_VARIETY = 'SAVE_VARIETY';
export const FETCH_VARIETIES = 'FETCH_VARIETIES';
export const EDIT_VARIETY = 'EDIT_VARIETY';
export const DELETE_VARIETY = 'DELETE_VARIETY';

export const SAVE_SIZE = 'SAVE_SIZE';
export const FETCH_SIZES = 'FETCH_SIZES';
export const EDIT_SIZE = 'EDIT_SIZE';
export const DELETE_SIZE = 'DELETE_SIZE';

export const SAVE_YEAR = 'SAVE_YEAR';
export const FETCH_YEARS = 'FETCH_YEARS';
export const EDIT_YEAR = 'EDIT_YEAR';
export const DELETE_YEAR = 'DELETE_YEAR';
export const CHANGE_YEAR = 'CHANGE_YEAR';
export const FETCH_CURRENT_YEAR = 'FETCH_CURRENT_YEAR';

export const SAVE_SETUP = 'SAVE_SETUP';
export const FETCH_SETUPS = 'FETCH_SETUPS';
export const EDIT_SETUP = 'EDIT_SETUP';
export const DELETE_SETUP = 'DELETE_SETUP';

export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const SAVE_BANK = 'SAVE_BANK';
export const FETCH_BANKS = 'FETCH_BANKS';
export const EDIT_BANK = 'EDIT_BANK';
export const DELETE_BANK = 'DELETE_BANK';
export const FETCH_TRANSACTIONS_OF_SINGLE_BANK = 'FETCH_TRANSACTIONS_OF_SINGLE_BANK';
export const FETCH_EXPENSES_OF_SINGLE_BANK = 'FETCH_EXPENSES_OF_SINGLE_BANK';

export const SAVE_EXPENSE_CATEGORY = 'SAVE_EXPENSE_CATEGORY';
export const FETCH_EXPENSE_CATEGORIES = 'FETCH_EXPENSE_CATEGORIES';
export const EDIT_EXPENSE_CATEGORY = 'EDIT_EXPENSE_CATEGORY';
export const DELETE_EXPENSE_CATEGORY = 'DELETE_EXPENSE_CATEGORY';

export const SAVE_EXPENSE = 'SAVE_EXPENSE';
export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_PARTIES_WITH_REMAINING_PACKETS = 'FETCH_PARTIES_WITH_REMAINING_PACKETS';
export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const EDIT_COUNTER = 'EDIT_COUNTER';

export const SAVE_RENT = 'SAVE_RENT';
export const FETCH_RENTS = 'FETCH_RENTS';
export const FETCH_RENTS_BY_PARTY_ID = 'FETCH_RENTS_BY_PARTY_ID';
export const EDIT_RENT = 'EDIT_RENT';
export const DELETE_RENT = 'DELETE_RENT';
export const FETCH_LAST_RENT = 'FETCH_LAST_RENT';
export const FETCH_NEW_RECEIPT_NUMBER_OF_RENT = 'FETCH_NEW_RECEIPT_NUMBER_OF_RENT';
