export const SAVE_PARTY = 'SAVE_PARTY';
export const FETCH_PARTIES = 'FETCH_PARTIES';
export const FETCH_PARTY = 'FETCH_PARTY';
export const EDIT_PARTY = 'EDIT_PARTY';
export const DELETE_PARTY = 'DELETE_PARTY';

export const SAVE_AVAK = 'SAVE_AVAK';
export const FETCH_AVAKS = 'FETCH_AVAKS';
export const FETCH_AVAKS_BY_PARTY_ID = 'FETCH_AVAKS_BY_PARTY_ID';
export const EDIT_AVAK = 'EDIT_AVAK';
export const DELETE_AVAK = 'DELETE_AVAK';

export const SAVE_JAVAK = 'SAVE_JAVAK';
export const FETCH_JAVAKS = 'FETCH_JAVAKS';
export const EDIT_JAVAK = 'EDIT_JAVAK';
export const DELETE_JAVAK = 'DELETE_JAVAK';
export const FETCH_AVAKS_OF_PARTY = 'FETCH_AVAKS_OF_PARTY';
export const FETCH_JAVAKS_BY_PARTY_ID = 'FETCH_JAVAK_LOTS_BY_AVAK_ID';

export const SAVE_JAVAK_LOT = 'SAVE_JAVAK_LOT';
export const DELETE_JAVAK_LOT = 'DELETE_JAVAK_LOT';
export const FETCH_JAVAK_LOTS = 'FETCH_JAVAK_LOTS';
export const FETCH_JAVAK_LOTS_BY_JAVAK_ID = 'FETCH_JAVAK_LOTS_BY_JAVAK_ID';
export const FETCH_JAVAK_LOTS_BY_AVAK_ID = 'FETCH_JAVAK_LOTS_BY_AVAK_ID';
export const REMOVE_TEMP_JAVAK_LOTS = 'REMOVE_TEMP_JAVAK_LOTS';

export const SAVE_TRANSACTION = 'SAVE_TRANSACTION';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_BY_PARTY_ID = 'FETCH_TRANSACTIONS_BY_PARTY_ID';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const SAVE_ITEM = 'SAVE_ITEM';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

export const SAVE_VARIETY = 'SAVE_VARIETY';
export const FETCH_VARIETIES = 'FETCH_VARIETIES';
export const EDIT_VARIETY = 'EDIT_VARIETY';
export const DELETE_VARIETY = 'DELETE_VARIETY';

export const SAVE_SIZE = 'SAVE_SIZE';
export const FETCH_SIZES = 'FETCH_SIZES';
export const EDIT_SIZE = 'EDIT_SIZE';
export const DELETE_SIZE = 'DELETE_SIZE';

export const SAVE_YEAR = 'SAVE_YEAR';
export const FETCH_YEARS = 'FETCH_YEARS';
export const EDIT_YEAR = 'EDIT_YEAR';
export const DELETE_YEAR = 'DELETE_YEAR';
export const CHANGE_YEAR = 'CHANGE_YEAR';
export const FETCH_CURRENT_YEAR = 'FETCH_CURRENT_YEAR';

export const SAVE_SETUP = 'SAVE_SETUP';
export const FETCH_SETUPS = 'FETCH_SETUPS';
export const EDIT_SETUP = 'EDIT_SETUP';
export const DELETE_SETUP = 'DELETE_SETUP';
